### ISSUE TITLE
SETTINGS_WEBTRANSPORT_MAX_SESSIONS safety

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#142]
MAX_SESSIONS is an HTTP/2-style limit. The spec currently says:
> The server MUST NOT close the connection if the client opens sessions exceeding this limit, as the client and the server do not have a consistent view of how many sessions are open due to the asynchronous nature of the protocol; instead, it MUST reset all of the CONNECT streams it is not willing to process with the HTTP_REQUEST_REJECTED status defined in [[HTTP3](https://ietf-wg-webtrans.github.io/draft-ietf-webtrans-http3/draft-ietf-webtrans-http3.html#HTTP3)].

Does this make us vulnerable to Rapid Reset-style attacks?

**Comment by LPardue** [comment]
This feels like the usual case where an HTTP/2 client might try and open more request streams than a server would allow. Each request over the concurrency limit must be reset. The client and server can have a different view of what the limit is due to SETTINGS racing. 

Per HTTP/2 security considerations, a server should provide defenses against protocol behaviour abuse; such as counting how many streams it resets (for any reason). Resetting a CONNECT stream due to MAX_SESSIONS limits seems like another variant. So maybe all we need to do is highlight this in the security considerations (maybe even just by citation).

**Comment by vasilvv** [comment]
Note that at least in this case, the client may exceed MAX_SESSIONS, but it is still bound by MAX_STREAMS for the overall request limit, which potentially limits amount of damage.

> such as counting how many streams it resets (for any reason)

That would be really bad for WebTransport though, since it's perfectly valid for application to reset data streams as much as it needs.

**Comment by LPardue** [comment]
> That would be really bad for WebTransport though, since it's perfectly valid for application to reset data streams as much as it needs.

Correct. The server needs to be smarter and consider the context of each reset, such as count the number of CONNECT requests rejected because the MAX_SESSIONS value didn't permit the stream. Counting valid uses of reset might be useful of acting on it can damage legitimate uses.

**Comment by ekinnear** [comment]
Discussed in editor's meeting: 

We need _some_ bound to enable you to prevent WT (or a single session) from using up all of the streams. However, the fact that this is running over HTTP/3 means that all of these are governed by HTTP/3 stream limits, which is already safe against rapid-reset style attacks. Put another way, you could just as effectively attack this with many GET requests as with attempts to open WT sessions.

Keeping a WT session from using all the streams is something for a WT-over-H3 flow control design to accomplish, but it's not needed as a security boundary to protect against this style of attack.
