### ISSUE TITLE
What does the server do if it receives a WebTransport request before the client's SETTINGS

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-ietf-webtrans-http3#143]
As discussed in #139 and during the WG session at IETF 118, it is possible for the server to receives a WebTransport request before the client's SETTINGS. In that scenario, there are multiple options possible
* have the server respond to the webtransport request assuming that the client supports webtransport
* have the server buffer this request until it receives the client's SETTINGS
* have the server buffer all bidirectional stream data until it receives the client's SETTINGS

It was raised during the meeting that the latter options might make servers vulnerable to malicious clients that send many requests without ever sending SETTINGS.

We need to specify how the server behaves in this scenario

**Comment by ekinnear** [comment]
Discussed in editor's meeting:

- Practically, if you support more than one WT version, you have to buffer CONNECT requests, until you know which version you're going to use (this arrives in the client's SETTINGS). The CONNECT itself might, in some WT version, contain information that depends on the WT version in use.
- When a new stream arrives, you have to parse far enough into it to determine that it's: 
    - a WebTransport stream
    - the WebTransport stream ID, so that you can tell if you have already received the CONNECT request/stream

Possible position: Therefore, you already have a buffering point on the server, so anything that we do around the client's SETTINGS arriving won't make a significant difference.

Server's that only support a single WT version can assume that it's that, or you can apply rules from all supported versions. If we're being careful in the future when we define new versions, we might take care to ensure that WT stream IDs and the surrounding items stay at the front so that you don't have to determine the version before you know what to do with the stream. Even if we do that, it doesn't tackle whether or not the CONNECT request has version-dependent headers.

One option is to say that we have an invariant across versions that all WT streams start with the type and the stream ID. We could potentially choose to include some indication of the version in the CONNECT request (either in :protocol or in a separate header, and then sort out all of the issues that arise if you send conflicting versions which should be possible but gross). All that would buy us is the ability to respond to incoming CONNECT requests _for WT versions that don't need non-default SETTINGS values_ and that also don't have a separate header in CONNECT requests that would carry such information.

**Comment by DavidSchinazi** [comment]
(speaking as individual contributor) We also have the ability to change the Upgrade Token, Unidirectional Stream Type, and Bidirectional Stream Signal Value. If a future version of WebTransport wants to change the wire format of streams (change the session ID at the start) or of the request (reuse an existing header to mean something else) then all it needs to do is change the corresponding value. That completely removes the need to wait for client settings.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting. Plan is to write one PR that resolves #135, #140, #141, and #143. That PR would say:
* client MUST wait for server settings
* endpoints MUST send SETTINGS_H3_DATAGRAM (however servers that want to validate this MUST need to take into account the fact that the request might arrive before the client's SETTINGS)
* client no longer sends the WEBTRANSPORT_MAX_SESSIONS setting
* Add a "Considerations for future versions of WebTransport" section that explain that if a future version of WebTransport changes the syntax of the request, it'll need to change the Upgrade Token. Similarly, changes to stream formats will require changes to the Unidirectional Stream Type and Bidirectional Stream Signal Value.
