### ISSUE TITLE
Http3Transport connection flow control

### ISSUE THREAD

**Issue by kixelated** [ietf-wg-webtrans/draft-ietf-webtrans-http3#22]
Note that all of the below works when you swap "server" and "client". I wanted to focus on a poor Javascript client implementation, but it's equally possible to run into these cases with a poor server implementation.

Let's say that you have a Http3Transport session that shares a connection with HTTP/3 or another Http3Transport session. 

### MAX_DATA
The client has limited buffer space and hypothetically advertises MAX_DATA of 1MB for the connection. If the server pushes 1MB of unprocessed data over a Http3Transport session, then it will prevent the server from sending data over the connection, including HTTP/3 responses and other Http3Transport sessions.

This can occur if the application does not accept all remote-created streams or does not fully read every stream. This will be VERY easy for a developer to mess up. It can also occur if the application can not process data faster than it is received.

In my case, the server creates unidirectional streams and pushes a large amount of media over them. The flow control limit would be hit if the Javascript application:

- Only accepts bidirectional streams (ex. initialization)
- Does not accept a unidirectional stream (ex. error or teardown)
- Does not fully read or abort every stream (ex. parsing error)
- Is not able to parse the media fast enough (ex. underpowered).

This is mostly intended behavior, otherwise these "bugs" would cause unbounded memory usage. However, the blast radius is bigger when sharing a connection. 

In my use-case, hitting the flow control limit would also block any HTTP/3 RPC calls or unrelated traffic on the connection. This introduces more scenarios for the connection to become deadlocked or generally stalled.

### MAX_STREAMS
HTTP/3 implementations use MAX_STREAMS to limit the number of simultaneous requests. This use-case no longer works when sharing a connection with a Http3Transport session, and HTTP/3 implementations must instead return explicit error status codes when this threshold is reached.

The same issues with MAX_DATA also apply to MAX_STREAMS. A Javascript application that fails to accept or read/abort every stream will consume flow control resources. This can manifest itself in strange ways, such as HTTP/3 being unable to create control streams, or simply being unable to create new request streams.

**Comment by LPardue** [comment]
Thanks for the salient overview, it makes it easier to understand your concerns.

My first comment would be that some of these points apply to QuicTransport too. Its just that their made worse by Http3Transport pooling allowing the mashing together of orthogonal protocols with no application-layer oversight. Just as you might interfere with a page load, a browser could easily interfere with your finely crafted application protocol. I would anticipate that, due to different browsers having different HTTP usage patterns, and different pages being composed differently by time, region, etc, one might find that Http3Transport apps subject to pooling would experience inconsistencies and transient issues. 

You rightly point out that the connection flow control is a shared resource. But the problems described seem to relate to stream flow control and overlooks the different flow control setting afforded by the Transport Parameters. A possible mitigation is to more tightly constrain the initial flow windows of server-initiated streams so that they can't interfere with requests. However, I still think that the notion of pooling together WebTransports in an uncoordinated fashion is going to manifest undesirable properties.

The MAX_STREAMS observation is a good one. I think the competition between request streams and client bidirectional streams is going to be hard to resolve.

**Comment by kixelated** [comment]
Yeah, and enforcing any per sort of per-session flow control might get difficult. You can only identify the protocol and session after you receive the first few bytes of each stream.

For example, assume a brand new connection (for simplicity only) and you receive a STREAM frame with id=100, offset=16, and size=1000. You don't know which protocol or session created this stream or the 25 preceding it.

**Comment by DavidSchinazi** [comment]
Chair notes from IETF 112 meeting: this needs more discussion (on the issue or mailing list)

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, consensus in room to:
* use a setting to limit number of WT sessions (see #34)
* figure out MAX_STREAMS, a way to limit the number of streams within a session
* abandon MAX_DATA as too hard, do not limit amount of data sent within a session (anyone can open a new issue to revisit this discussion if they have a concrete proposal on how to do this)
* let QUIC take care of MAX_STREAM_DATA

**Comment by ekinnear** [comment]
Capsule DT is doing all of the above bullet points except the second one, for which I opened #85.
