### ISSUE TITLE
Http3Transport Unidirectional Streams section is unclear

### ISSUE THREAD

**Issue by ianswett** [ietf-wg-webtrans/draft-ietf-webtrans-http3#24]
It talks about the HTTP/3 control stream, which doesn't seem very relevant to establishing new unidirectional streams for WebTransport.

Also, I'm unclear on why the HTTP/3 frame type is 54, instead of 41 like the client initiated bidi streams.  Could all WebTransport streams not use a single HTTP/3 frame type?

https://github.com/vasilvv/webtransport/blob/master/draft-vvv-webtransport-http3.md#unidirectional-streams

**Comment by afrind** [comment]
I think the text says "control stream type" but I think it should just read "stream type", per HTTP/3 section 6.2:

> The purpose is indicated by a stream type, which is sent as a variable-length integer at the start of the stream.

I agree with Ian that there could be a single uni stream type used for both client and server side streams, since the only difference is their direction, and that's encoded in the stream ID.

**Comment by afrind** [comment]
Ah, I re-read the spec and now I understand.

41 is the unidirectional stream type, which is used as a prefix at the beginning of any WebTransport uni stream in either direction.

54 is a frame type that appears at the beginning of a client-initiated bidi stream, since the H3 spec says the server treats all client-bidi streams as request/response.  I think the new frame is underspecified in the document.  It should be required to have zero length.

There's a potential hazard with using a frame to identify the client-initiated bidi WT streams, which is that unknown frame types are allowed to be ignored.  Hopefully no implementation would set the WT SETTINGS field without also having a parser that understands these.

**Comment by afrind** [comment]
Agh still reading too quickly!

I see the definition of the frame has no length, which is odd because it is not a proper HTTP/3 frame, per H3 Section 7.1:

```
7.1. Frame Layout
All frames have the following format:

HTTP/3 Frame Format {
  Type (i),
  Length (i),
  Frame Payload (..),
}
```

Of course this is an extension so we can override this, but it's probably easier on everyone's parser if all frames have both type and length.  We can just state the frame length 0 means "to the end of the stream" in this case?

Also, the section specifying how uni and bidi streams work have the 54 and 41 opposite from how they appear in the registration sections.

**Comment by ianswett** [comment]
I believe the QUIC WG decided that TV frames were fine in extensions, but that we weren't going to use them in the core spec?  That being said, maybe the HTTP/3 draft should be updated to note this fact.

Given an unknown type is an immediate error condition and a length of 0 is a valid length for frames in general, I think TV is preferable.  Given this is not described in the core spec, it should be called out no matter how it's encoded on the wire.

I'm still confused about 54 vs 41, but I'm sure it can be clarified.

**Comment by LPardue** [comment]
You can't omit the length field, but we did discuss that 0-length would be fine on a per-frame definition basis.

In H3, unknown frames types are simply ignored. Nrgoyiation is not required to negotiate extensions that do not change H3 semantic.

**Comment by ianswett** [comment]
The length issue was discussed at length on the issue: https://github.com/quicwg/base-drafts/issues/1885 and in Tokyo: https://github.com/quicwg/wg-materials/blob/master/interim-19-01/minutes.md#issue-1885data-frame-encoding-is-inefficient-for-long-dynamically-generated-bodies

I thought the conclusion from Tokyo was that you could do this in an extension, but that's not particularly clear from the issue or minutes.  The discussion both on the issue and in person was fairly all over the place, so it's difficult to summarize.

We did make 0 a valid DATA length as part of this series of changes, which makes declaring it a special value now quite odd.

**Comment by afrind** [comment]
I view it slightly differently, which is that the WebTransport Frame *is* zero length (has no payload), but it's effect is that it declares the remainder of the frame to be unframed.

**Comment by ianswett** [comment]
I can't say that I find that intuitive, so it definitely needs to be written up, but that accomplishes what I want, so it WFM.

**Comment by ianswett** [comment]
I split off the TV vs TLV with 0 length question into https://github.com/vasilvv/webtransport/issues/26

**Comment by vasilvv** [comment]
Stream types were referred to as control stream types in older versions of HTTP/3 draft, hence the name.  I fixed this a while ago, so closing this.
