### ISSUE TITLE
RESET_STREAM error codes

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#40]
If we are going to let the API users supply their own stream reset code, we should figure out how this is represented on the wire.  We could potentially use the error codes as-is and say they mean different things for WebTransport streams than what they mean for normal streams, but I am not sure this is sound as we don't always know that a stream is a WebTransport stream at the time we process the reset (also this sounds like a pain to implement).

One possibility would be to reserve a block within HTTP/3 error code space.  However, since HTTP/3 error codes contain GREASE code-points throughout, we might end up having to "de-grease" and "re-grease" them as the largest continuous block only has 255 codepoints available.

Alternatively, if we decide to just send RESET_STREAM as a part of CONNECT stream due to issues in #31, we could just send the error code there, and keep one single code for user-initiated termination.

Whatever we decide here should probably work for H/2 as well.

cc @martinthomson

**Comment by DavidSchinazi** [comment]
Are application developers asking for custom reset error codes? Making reset unreliable and non-customizable would be much easier if that's sufficient for everyone's needs.

**Comment by vasilvv** [comment]
Reset error codes are special in the sense that they are reliably delivered by the transport (unlike the data, which all can be lost to a reset).  So I imagine an application would want to be able to tell apart a regular reset (e.g. due to stream TTL expiring), vs reset due to an error.

@kixelated might have opinions on this, since he filed #31.

**Comment by LPardue** [comment]
We went through a concerted effort to reduce the number of H3 error codes. Partly because knowing when to use the right code (from an implementation persepctive) can be hard. 

H2's space is small, I don't know if the experts would allow one application to reserve a large block.

At a minimum we probably need a WEBTRANS_NO_ERROR. Maybe there are some error codes for "Web transport wire protocol error". Anticipating more specific error codes for apps using webtransport is hard. Some motivating use cases might help.

**Comment by vasilvv** [comment]
> H2's space is small, I don't know if the experts would allow one application to reserve a large block.

It's 32-bit, so I think we could probably get 16 bits worth of error codes.

**Comment by LPardue** [comment]
Ah quire right, I was getting mixed up with frame type which is 8 bits. But still, reserving half the code points for one usage of H2 seems overboard. 

Given that H2 suffices with about a dozen error codes I really wonder what WebTransport thinks it can achieve by using so many. Maybe the ask is for a "retire stream with a status"? In which case an alternate design would be to add a control frame for webstransport that contains your own space or possibly a reason phrasr and then a generic error code such as WEBTRANS_STREAM_ABORT to disambiguate it from other H3 errors.

**Comment by vasilvv** [comment]
I think it's 1/65536th of the error space, not 1/2.

WebTransport *by itself* does not need that many error codes (I have so far three or four in the code that I will write a PR as soon as I'm done); the question here is what do applications running on top of it want.

**Comment by kixelated** [comment]
The [JS API](https://w3c.github.io/webtransport/#web-transport-close-info) exposes connection error codes, so it's something the transport would need to support. I think removing them would be a W3C conversation.

Actually for my application, we wanted to signal when the connection was terminated gracefully versus an unexpected error. We tried using CONNECTION_CLOSE with application error codes but the QuicTransport implementation in Chrome always raised "Connection Lost" regardless of the code. We had to resort to making a new stream and our own, high priority message when the connection was closed. This also meant waiting for the message to be acknowledged before actually closing the connection, otherwise the message would be lost.

So yeah, I think immediately closing a connection with an error code is useful functionality, hence why it's in QUIC as well.

**Comment by LPardue** [comment]
Would it work to just defer that the registration to applications over WebTransport? I appreciate it's nice to have a contiguous block but there's hardly much churn in that registry and I don't know what practical benefit a contiguous range adds for distinct uses of WebTransport. I'm confused if you're attempting to reserve a block that is then allocated via some sub-protocol negotiation, or if you intend to run a registration scheme inside your reserved block. Or something else.

**Comment by vasilvv** [comment]
Are you suggesting that we should let WebTransport applications send arbitrary HTTP/3 error codes?  That could work, but I am not sure what are the security consequences of that.  If we only reserve a block, the error codes outside of that block are "privileged", i.e. only the browser (but not the untrusted web application) can send them.

**Comment by LPardue** [comment]
That's a good point and puts more weight behind reserving a block that can only be used by the WebTransport API.

**Comment by DavidSchinazi** [comment]
@kixelated could you elaborate on how your application reacts differently to graceful termination of a stream vs unexpected error? I'm just curious to know what you use this for.

**Comment by vasilvv** [comment]
Makes sense, though this is for an entire session (see #41).  Here we're discussing individual streams.

**Comment by LPardue** [comment]
I'm finding the mention of CONNECTION_CLOSE slightly confusing since this thread is about stream resets. 

The JS API doesn't mention if CONNECTION_CLOSE is a transport-level or application-level close, it really should. 

The HTTP-based WebTransports support graceful connection close via GOAWAY.

Applications built on WebTransport might be able to harness these properties, or they might need to create a control channel per session that could then behave exactly how they want, without the overhead of IETF registries.

**Comment by kixelated** [comment]
Oh sorry, for some reason I thought this was for the entire connection.

Resetting a stream with an error code is less useful, but again it's in the [JS API](https://w3c.github.io/webtransport/#dom-outgoingstream-abortwriting). RESET_STREAM is useful for my application because the streams transfer a large amount of data, which may be blocked, but I don't have a use-case for specific error codes.

**Comment by martinthomson** [comment]
Just to close the loop here.  We talked about this in the context of W3C and decided that we'd like to have some number of error code points just for web transport.  256 was the initial suggestion; 100 might work; 31 was considered too small.  @DavidSchinazi pointed out that we can play FizzBuzz and step carefully around the reserved greasing points so that a contiguous block is presented to applications even if the underlying code points are not contiguous.

**Comment by LPardue** [comment]
FWIW, where I said

> The JS API doesn't mention if CONNECTION_CLOSE is a transport-level or application-level close, it really should.

there is already an issue for it https://github.com/w3c/webtransport/issues/80

**Comment by vasilvv** [comment]
> Just to close the loop here. We talked about this in the context of W3C and decided that we'd like to have some number of error code points just for web transport. 256 was the initial suggestion; 100 might work; 31 was considered too small. @DavidSchinazi pointed out that we can play FizzBuzz and step carefully around the reserved greasing points so that a contiguous block is presented to applications even if the underlying code points are not contiguous.

We discussed this at May 2021 interim, and there appeared to be an agreement in the room that we should do that.  I'll write up a PR with some set of 256 points.
