### ISSUE TITLE
Error codes for closing the session

### ISSUE THREAD

**Issue by vasilvv** [ietf-wg-webtrans/draft-ietf-webtrans-http3#41]
Since the API was based off QuicTransport, the API document currently has a method to close the session, with both an error code and a reason string (modeled off QUIC CONNECTION_CLOSE): <https://w3c.github.io/webtransport/#web-transport-close-info>.

We could attempt to reset the CONNECT stream, but that would imply that it's always reset, and will not let us supply a reason string.  I think the easiest way would be to send trailers on the CONNECT stream.

**Comment by afrind** [comment]
If we want to allow trailers (or any non DATA frames) on the CONNECT stream, we need to add text allowing that.

From the H3 spec:

Once the CONNECT method has completed, only DATA frames are permitted to be sent on the stream.  Extension frames MAY be used if specifically permitted by the definition of the extension.


From: Victor Vasiliev ***@***.***>
Reply-To: ietf-wg-webtrans/draft-ietf-webtrans-http3 ***@***.***>
Date: Tuesday, March 30, 2021 at 2:15 PM
To: ietf-wg-webtrans/draft-ietf-webtrans-http3 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ietf-wg-webtrans/draft-ietf-webtrans-http3] Error codes for closing the session (#41)


Since the API was based off QuicTransport, the API document currently has a method to close the session, with both an error code and a reason string (modeled off QUIC CONNECTION_CLOSE): https://w3c.github.io/webtransport/#web-transport-close-info<https://w3c.github.io/webtransport/#web-transport-close-info>.

We could attempt to reset the CONNECT stream, but that would imply that it's always reset, and will not let us supply a reason string. I think the easiest way would be to send trailers on the CONNECT stream.

**Comment by afrind** [comment]
Issue #27 also discusses adding a GOAWAY-type frame on the CONNECT stream.  If we did that we could add an error and reason there as an alternative to trailers.
