### ISSUE TITLE
Client handling of HTTP redirect

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-ietf-webtrans-http3#61]
We need to specify what the client should do if the server responds to the Extended CONNECT request with a 3XX status code. See [BCP56bis s4.3](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-bcp56bis-13#section-4.3).

**Comment by vasilvv** [comment]
For what it's worth, last time we discussed this in W3C, the agreement was "we should not support this, the application developers are welcome to add a redirect layer on their own".

**Comment by DavidSchinazi** [comment]
Chair notes from IETF 112 meeting: we will analyze BCP56bis and follow the recommendations there

**Comment by vasilvv** [comment]
https://www.rfc-editor.org/rfc/rfc9205.html#name-redirection says:

> As noted in [[HTTP](https://www.rfc-editor.org/rfc/rfc9205.html#HTTP)], a user agent is allowed to automatically follow a 3xx redirect that has a Location response header field, even if they don't understand the semantics of the specific status code. However, they aren't required to do so; therefore, if an application using HTTP desires redirects to be automatically followed, it needs to explicitly specify the circumstances when this is required.

I assume this means that we are not required to make the user agent automatically follow redirects.  Servers may return 3xx (in which case no WebTransport session is created), and we may define some form of propagating that information in the browser, but as far as I can tell, there isn't much to say in the draft.

**Comment by DavidSchinazi** [comment]
BCP56bis (now published as RFC 9205) [states in s4.3](https://datatracker.ietf.org/doc/html/rfc9205#section-4.3):
> Redirect handling:  Applications need to specify how redirects are expected to be handled

Therefore, we need to be explicit in the WebTransport document: we need to pick which variation of "the client MAY/SHOULD/MUST follow redirects" we want. That'll make it clear to application developers whether or not they can use redirects.

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 114, Folks in the room strongly preferred a mandatory statement (MUST or MUST NOT instead of SHOULD/MAY/SHOULD NOT). Majority of the room preferred MUST over MUST NOT. Victor believes that some folks who would have objections because this was hard in WebSockets are not in the room, so we are not declaring consensus today and will continue discussing on this issue. @vasilvv is taking an action item to get these folks to chime in on this issue.

**Comment by guoye-zhang** [comment]
If redirection is support, what does a client do with 303 that changes the method to GET? Treat it as a failure?

**Comment by DavidSchinazi** [comment]
That's a good point, we should probably ban 300, 303, 304, 305, and 306.

**Comment by ricea** [comment]
Redirects were banned for WebSockets because of the following attack:

1. A page takes the address of a WebSocket as a query parameter, validates the origin, and connects to it if the origin is correct.
2. The same origin has an open redirect.
3. An attacker sets the query parameter to something like https://target.domain/redirect?href=https://attacker.domain/fake-endpoint
4. The page believes it's talking to a trusted endpoint, when actually it's talking to an attacker-controller endpoint.

Open redirects are surprisingly common (even google.com has one), but I don't know how likely it is that a page will take an endpoint as a query parameter.

From an implementation point of view, not supporting redirects has made Chrome's WebSocket implementation significantly simpler and more secure.

As a general principle, I would recommend WebTransport avoid adopting any HTTP features that are not strictly necessary for it to function. The most difficult bugs in Chrome's WebSocket implementation come from supporting HTTP features.

**Comment by DavidSchinazi** [comment]
Chair: discussed in editor's meeting, folks would prefer to disallow redirect for now and add them in a separate doc later if we really need them. Let's discuss at 116.

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 116. Consensus in room was to not handle redirect transparently at the IETF WebTransport layer. W3C will decide whether a 3xx can be sent by the server and whether that will be reported to JavaScript.
