### ISSUE TITLE
Folding datagrams/streams into the CONNECT stream

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-ietf-webtrans-http3#66]
Should the protocol share framing semantics with the HTTP/2 draft so that it is easy/easier to take datagrams or streams and put them on the CONNECT stream?

Should it be possible to use that mechanism, or should it instead be forbidden?

As much as possible, it would be desirable to have the forwarding logic be fairly uniform across different protocol versions.  Right now, we have two almost completely different protocols.

**Comment by afrind** [comment]
I was discussing this with @ekinnear and @vasilvv.  What happens when an H3 WT server receives "version independent" WT framing on its CONNECT stream.

Since WT over H3 requires H3 datagrams, then there is no need to fold datagrams into the CONNECT stream.  There shouldn't be a need to fold streams either, unless you want to defeat QUIC stream limits :) 

Allowing this would also increase work to implement an H3 only WT client/server: you have to re-implement QUIC over an HTTP byte-stream just in case the peer decides to send you "version independent" WT.

Right now I think they are totally different and never the twain shall meet.  Proxies can convert between the two versions.  If we did that, should we have different upgrade tokens?

**Comment by vasilvv** [comment]
Is this issue still relevant now that we have the outcome of HTTP Datagram Design Team?

**Comment by DavidSchinazi** [comment]
@martinthomson gentle ping

**Comment by DavidSchinazi** [comment]
Actually never mind, this is blocked on the capsule design team - the output of that design team will decide on whether the h2 capsules are allowed in h3 or not
