### ISSUE TITLE
When closing a session, should the read side of the request stream be reset?

### ISSUE THREAD

**Issue by marten-seemann** [ietf-wg-webtrans/draft-ietf-webtrans-http3#78]
After sending the CLOSE_WEBTRANSPORT_SESSION capsule and sending the FIN on the stream, it would make sense to also stop reading on the stream (by sending a STOP_SENDING). Should that be the recommended behavior in the spec?

**Comment by DavidSchinazi** [comment]
Chair: discussed at IETF 114, consensus to allow but not require sending STOP_SENDING

**Comment by afrind** [comment]
The spec currently reads:

```
A CLOSE_WEBTRANSPORT_SESSION capsule MUST be followed by a FIN on the sender
side.  If any additional stream data is received on the CONNECT stream after
CLOSE_WEBTRANSPORT_SESSION, the stream MUST be reset with code
H3_MESSAGE_ERROR.  The recipient MUST close the stream upon receiving a FIN.
If the sender of CLOSE_WEBTRANSPORT_SESSION does not receive a FIN after some
time, it SHOULD send STOP_SENDING on the CONNECT stream.
```

So it currently recommends setting a timer and then issuing a STOP_SENDING.  I guess the request here is to send indicate the sender of CLOSE_WEBTRANSPORT_SESSION may send the STOP_SENDING immediately.  I'm going to remove the bit about the timer since it's not really relevant?  If the closing endpoint wants to wait to see if there's any other messages in flight on the CONNECT stream that's fine.  The CLOSE_WEBTRANSPORT_SESSION + FIN + must-respond-with-FIN is an implicit STOP_SENDING.
